### ISSUE TITLE
Test erorrs (Genesis and PDB dimred)

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-continuousflex#138]
I have strange testing errors related to pdb_dimred. I don't know if you will be able to reproduce them, the problem might be the version of new packages, since I am testing on a frensh installation of scipion (installation from scratch starting from a new miniconda). I will past my pip list in a comment.

Testing subtomogram synthesis:

```
Creating project at /media/SharedDisk/ScipionProjects/projects/TestSubtomogramSynthesize/project.sqlite
>>>> python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download nma_V2.0  -u https://raw.githubusercontent.com/continuousflex-org/testdata-continuousflex/main
Selected datasets: nma_V2.0
Local copy of dataset nma_V2.0 detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestSubtomogramSynthesize" "Runs/000002_ProtImportPdb/logs/run.db" 2'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestSubtomogramSynthesize" "Runs/000040_FlexProtNMA/logs/run.db" 40'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestSubtomogramSynthesize" "Runs/000088_FlexProtSynthesizeSubtomo/logs/run.db" 88'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestSubtomogramSynthesize" "Runs/000207_FlexProtDimredPdb/logs/run.db" 207'

*************** last 50 lines of STD OUT *********************

> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00014_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00014_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00015_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00015_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00016_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00016_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00017_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00017_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00018_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00018_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00019_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00019_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00020_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00020_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00021_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00021_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00022_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00022_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00023_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00023_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00024_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00024_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00025_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00025_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00026_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00026_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00027_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00027_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00028_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00028_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00029_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00029_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00030_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00030_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00031_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00031_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00032_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00032_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00033_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00033_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00034_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00034_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00035_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00035_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00036_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00036_df.pdb 
> Wrinting dcd file Runs/000207_FlexProtDimredPdb/extra/coords.dcd
FAILED: readInputFiles, step 1, time 2022-11-20 10:50:53.871743
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 1/3)

*************** end of STD OUT *********************


*************** last 50 lines of STD ERR *********************

/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/protocols/utilities/pdb_handler.py:60: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  atomNum[np.where(atomNum == "*****")[0]] = "-1"
Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
    self._run()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
    resultFiles = self._runFunc()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
    return self._func(*self._args)
  File "/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/protocols/protocol_pdb_dimred.py", line 145, in readInputFiles
    numpyArr2dcd(pdbs_arr, self._getExtraPath("coords.dcd"))
  File "/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/protocols/utilities/genesis_utilities.py", line 395, in numpyArr2dcd
    nframe, natom, _ = arr.shape
ValueError: not enough values to unpack (expected 3, got 1)
Protocol failed: not enough values to unpack (expected 3, got 1)

*************** end of STD ERR *********************

[   FAILED ] TestSubtomogramSynthesize.test_synthesize_all


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/tests/test_workflow_subtomogram_synthesize.py", line 134, in test_synthesize_all
    self.launchProtocol(protpdbdimred3)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 116, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol pdb dimred execution failed. See last log lines above for more details.
```

Testing tomoflow:
```
reating project at /media/SharedDisk/ScipionProjects/projects/TestTomoFlow/project.sqlite
>>>> python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download nma_V2.0  -u https://raw.githubusercontent.com/continuousflex-org/testdata-continuousflex/main
Selected datasets: nma_V2.0
Local copy of dataset nma_V2.0 detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomoFlow" "Runs/000002_ProtImportPdb/logs/run.db" 2'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomoFlow" "Runs/000040_FlexProtNMA/logs/run.db" 40'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomoFlow" "Runs/000088_FlexProtSynthesizeSubtomo/logs/run.db" 88'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomoFlow" "Runs/000207_FlexProtDimredPdb/logs/run.db" 207'

*************** last 50 lines of STD OUT *********************

Logging configured. STDOUT --> Runs/000207_FlexProtDimredPdb/logs/run.stdout , STDERR --> Runs/000207_FlexProtDimredPdb/logs/run.stderr
RUNNING PROTOCOL -----------------
Protocol starts
Hostname: PC4-0002-D
PID: 97587
pyworkflow: 3.0.27
plugin: continuousflex
plugin v: 3.2.0
currentDir: /media/SharedDisk/ScipionProjects/projects/TestTomoFlow
workingDir: Runs/000207_FlexProtDimredPdb
runMode: Continue
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
STARTED: readInputFiles, step 1, time 2022-11-20 10:51:52.038415
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00001_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00001_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00002_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00002_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00003_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00003_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00004_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00004_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00005_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00005_df.pdb 
> Reading pdb file Runs/000088_FlexProtSynthesizeSubtomo/extra/00006_df.pdb ...
Warning : Can not read PDB file Runs/000088_FlexProtSynthesizeSubtomo/extra/00006_df.pdb 
> Wrinting dcd file Runs/000207_FlexProtDimredPdb/extra/coords.dcd
FAILED: readInputFiles, step 1, time 2022-11-20 10:51:52.066251
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 1/3)

*************** end of STD OUT *********************


*************** last 50 lines of STD ERR *********************

/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/protocols/utilities/pdb_handler.py:60: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  atomNum[np.where(atomNum == "*****")[0]] = "-1"
Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
    self._run()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
    resultFiles = self._runFunc()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
    return self._func(*self._args)
  File "/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/protocols/protocol_pdb_dimred.py", line 145, in readInputFiles
    numpyArr2dcd(pdbs_arr, self._getExtraPath("coords.dcd"))
  File "/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/protocols/utilities/genesis_utilities.py", line 395, in numpyArr2dcd
    nframe, natom, _ = arr.shape
ValueError: not enough values to unpack (expected 3, got 1)
Protocol failed: not enough values to unpack (expected 3, got 1)

*************** end of STD ERR *********************

[   FAILED ] TestTomoFlow.test_all


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/tests/test_workflow_TomoFlow.py", line 77, in test_all
    self.launchProtocol(protpdbdimred)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 116, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol PCA on groundtruth PDBs execution failed. See last log lines above for more details.
```

Test Genesis (the first test fails, the second passes):
```

Creating project at /media/SharedDisk/ScipionProjects/projects/testGENESIS/project.sqlite
>>>> python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download nma_V2.0  -u https://raw.githubusercontent.com/continuousflex-org/testdata-continuousflex/main
Selected datasets: nma_V2.0
Local copy of dataset nma_V2.0 detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/testGENESIS" "Runs/000002_ProtImportVolumes/logs/run.db" 2'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/testGENESIS" "Runs/000056_ProtImportPdb/logs/run.db" 56'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/testGENESIS" "Runs/000094_ProtGenerateTopology/logs/run.db" 94'

*************** last 50 lines of STD OUT *********************

Logging configured. STDOUT --> Runs/000094_ProtGenerateTopology/logs/run.stdout , STDERR --> Runs/000094_ProtGenerateTopology/logs/run.stderr
RUNNING PROTOCOL -----------------
Protocol starts
Hostname: PC4-0002-D
PID: 97846
pyworkflow: 3.0.27
plugin: continuousflex
plugin v: 3.2.0
currentDir: /media/SharedDisk/ScipionProjects/projects/testGENESIS
workingDir: Runs/000094_ProtGenerateTopology
runMode: Continue
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
STARTED: convertInput, step 1, time 2022-11-20 10:52:04.042713
FINISHED: convertInput, step 1, time 2022-11-20 10:52:04.088229
STARTED: preparePSF, step 2, time 2022-11-20 10:52:04.100789
FINISHED: preparePSF, step 2, time 2022-11-20 10:52:04.120890
STARTED: runPSF, step 3, time 2022-11-20 10:52:04.169819
FAILED: runPSF, step 3, time 2022-11-20 10:52:04.207430
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 3/5)

*************** end of STD OUT *********************


*************** last 50 lines of STD ERR *********************

/bin/sh: 1: vmd: not found
Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
    self._run()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
    resultFiles = self._runFunc()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
    return self._func(*self._args)
  File "/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/protocols/protocol_generate_topology.py", line 169, in runPSF
    runCommand("vmd -dispdev text -e %s > %s.log " % (fnPSFgen, outputPrefix))
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 70, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'vmd -dispdev text -e Runs/000094_ProtGenerateTopology/extra/psfgen.tcl > Runs/000094_ProtGenerateTopology/extra/output.log ' returned non-zero exit status 127.
Protocol failed: Command 'vmd -dispdev text -e Runs/000094_ProtGenerateTopology/extra/psfgen.tcl > Runs/000094_ProtGenerateTopology/extra/output.log ' returned non-zero exit status 127.

*************** end of STD ERR *********************

[   FAILED ] testGENESIS.test1_EmfitVolumeCHARMM


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-continuousflex/continuousflex/tests/test_workflow_GENESIS.py", line 65, in test1_EmfitVolumeCHARMM
    self.launchProtocol(protGenTopo)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 116, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol continuousflex - generate topology execution failed. See last log lines above for more details.
```

**Comment by mms29** [comment]
Strange, I can run the test on my machine with no errors... 

Suggestions : 

**Testing subtomogram synthesis/ Testing Tomoflow**
It looks like the reader can not read the PDBs, most likely because the file does not exists or is empty. can you verify ? (e.g.  Runs/000088_FlexProtSynthesizeSubtomo/extra/00001_df.pdb)

**Testing Genesis**
`/bin/sh: 1: vmd: not found`
Is VMD installed and available in your PATH ?

**Comment by MohamadHarastani** [comment]
I think I know what is the problem with the pdb parser. Something has changed very recently related to PDB in xmipp. The errors I reported yesterday are using xmipp latest devel branch. On another computer where xmipp is compiled two weeks ago I see this when I did git pull:

```
(base) harastam@pc4-0002-a:~/scipion3/xmipp/src/xmipp$ git pull
remote: Enumerating objects: 616, done.
remote: Counting objects: 100% (547/547), done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 616 (delta 404), reused 491 (delta 372), pack-reused 69
Receiving objects: 100% (616/616), 298.70 KiB | 7.66 MiB/s, done.
Resolving deltas: 100% (411/411), completed with 46 local objects.
From https://github.com/I2PC/xmipp
   358666eb..d432403a  devel                -> origin/devel
   2202a06e..d5c11ccb  ds_flexalign_opt     -> origin/ds_flexalign_opt
 * [new branch]        ds_phantomMovieNoise -> origin/ds_phantomMovieNoise
 * [new branch]        ef_subtract_projection_fix2 -> origin/ef_subtract_projection_fix2
 * [new branch]        jmk_pdb_2            -> origin/jmk_pdb_2
   67afbefb..045fee6b  jmk_pseudoatoms      -> origin/jmk_pseudoatoms
   68f6c29b..21261ba0  master               -> origin/master
 * [new branch]        mit_deepconsensus_3d -> origin/mit_deepconsensus_3d
   857927e2..01ec482d  olz_new_alignment_methods -> origin/olz_new_alignment_methods
   4f7c8e68..03ccdec2  olz_new_alignment_methods_cuda -> origin/olz_new_alignment_methods_cuda
 * [new branch]        release-3.22.11      -> origin/release-3.22.11
 * [new tag]           v3.22.11-Iris        -> v3.22.11-Iris
Updating 358666eb..d432403a
Fast-forward
 .github/workflows/main.yml                         |   6 +-
 CHANGELOG.md                                       |  47 ++++-
 src/xmipp/bindings/python/python_constants.cpp     |   3 +
 src/xmipp/libraries/data/pdb.cpp                   |  96 +++++++---
 src/xmipp/libraries/data/pdb.h                     |  20 +-
 src/xmipp/libraries/data/symmetries.cpp            |   2 +
 .../reconstruction/pdb_reduce_pseudoatoms.cpp      |   8 +-
 .../reconstruction/subtract_projection.cpp         | 204 ++++++++++++++++-----
 .../libraries/reconstruction/subtract_projection.h |  21 ++-
 src/xmipp/tests/test_programs_xmipp.py             |   5 +-
 xmipp                                              |   5 +-
 11 files changed, 330 insertions(+), 87 deletions(-)
```
So xmipp_nma_pdb_deform is doing something strange to the pdbs so they are not readable by the parser. They are also not readable in Chimera.

**Comment by MohamadHarastani** [comment]
It looks to me that this merge caused the problem
https://github.com/I2PC/xmipp/pull/659

**Comment by MohamadHarastani** [comment]
Found it.. it is the xmipp_volume_from_pdb that is damaging the pdbs! I will report that to xmipp

**Comment by MohamadHarastani** [comment]
Submitted an issue to https://github.com/I2PC/xmipp/issues/675
We can close this issue when the issue in xmipp is solved...

**Comment by mms29** [comment]
Before closing the issue, I will add an handler for such errors in the parser so that it prints what cause the issue when reading the PDB.

**Comment by MohamadHarastani** [comment]
Remi! I also noticed that for pdb dimred, providing a filepath does not work (is not allowed to Execute) since probably one of the files was set to be important.

**Comment by mms29** [comment]
I already had this issue, however, there is no "allow null" in the parameters, so I did not find the origin of the issue. When it happens (not every time), I just do "save" and open again the protocol which allow to execute. I noticed this problem with other protocols from Xmipp, I thought it was just a bug of the UI

**Comment by MohamadHarastani** [comment]
Actually, you can add a new attribute `allowsNull = True` to any variable in the form ([example](https://github.com/scipion-em/scipion-em-continuousflex/blob/master/continuousflex/protocols/protocol_denoise_volumes.py#L92)). This will sort out this problem. This can be very useful when you have multiple options of input.
